// Generated by https://quicktype.io

export interface IPData {
    ip:       string;
    location: Location;
    timezone: string;
    city:     string;
    isp:      string;
}

export interface Location {
    latitud:  number;
    longitud: number;
}
